
class Parameters:
    TEMPERATURE = "Temperature"
    HUMIDITY = "Humidite"
    PM2_5 = "PM2.5"
    PM10 = "PM10"
    C7H8 = "C7H8"
    C3H6O = "C3H6O"
    H2 = "H2"
    NOX = "NOx"
    CL2 = "CL2"
    O3 = "O3"
    BENZENE = "Benzene"
    HEXANE = "Hexane"
    ALCOOL = "Alcool"
    METHANE = "Methane"
    LPG = "LPG"
    HS2 = "HS2"
    CO = "CO"
    CO2 = "CO2"
    NH3 = "NH3"
    AIR_QUALITY = "Air quality"